### ISSUE TITLE
fatal: This operation must be run in a work tree

### ISSUE THREAD

**Issue by wwng2333** [SudaMod/android#11]
```bash
Shared project LineageOS/android_hardware_ril found, disabling pruning.
Shared project LineageOS/android_hardware_qcom_bt found, disabling pruning.
Shared project LineageOS/android_hardware_qcom_bt found, disabling pruning.
Shared project LineageOS/android_hardware_qcom_wlan found, disabling pruning.
Shared project LineageOS/android_hardware_qcom_wlan found, disabling pruning.
Syncing work tree:   7% (43/602)  fatal: This operation must be run in a work tree
Traceback (most recent call last):
  File "/home/SudaMod/.repo/repo/main.py", line 531, in <module>
    _Main(sys.argv[1:])
  File "/home/SudaMod/.repo/repo/main.py", line 507, in _Main
    result = repo._Run(argv) or 0
  File "/home/SudaMod/.repo/repo/main.py", line 180, in _Run
    result = cmd.Execute(copts, cargs)
  File "/home/SudaMod/.repo/repo/subcmds/sync.py", line 821, in Execute
    project.Sync_LocalHalf(syncbuf, force_sync=opt.force_sync)
  File "/home/SudaMod/.repo/repo/project.py", line 1327, in Sync_LocalHalf
    self._InitWorkTree(force_sync=force_sync)
  File "/home/SudaMod/.repo/repo/project.py", line 2486, in _InitWorkTree
    raise GitError("cannot initialize work tree")
error.GitError: cannot initialize work tree
```

**Comment by wuyi-levard** [comment]
看看同步时的提示，是那个文件，删了重新同步也可以，按提示直接覆盖也可以
